name: Lint and Test

on: push

jobs:
  build:
    name: Lint and Test

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install .[test]

      - name: Lint with Black
        run: black app --check --verbose

      - name: Run unit tests with Pytest
        run: pytest --verbose
        env:
          DATABASE_URI: "sqlite://local.db"